/* ColbyMajorGuide: turn a published seats.json into the seats.data.js the page loads.
 *
 *   node build-seats.mjs [path/to/seats.json]     default: ./seats.json
 *
 * Exits non-zero on any problem, the same bargain verify.mjs makes: the page will
 * happily render whatever it is handed, so the checking has to happen here. A feed
 * that fails this script must not be published, because a wrong seat count is worse
 * than none. A student would plan around it.
 *
 * Why a .js and not the .json itself: index.html ships
 * Content-Security-Policy connect-src 'none' and is meant to run from a file:// copy
 * with no server, so the page cannot fetch a sibling file. It loads a script that
 * assigns a global, exactly as data.js does. See SEATS.md for the contract.
 */
import fs from 'node:fs';

const src = process.argv[2] || 'seats.json';
const problems = [];
const notes = [];

if (!fs.existsSync(src)) {
  console.error('no such file: ' + src + '\nSEATS.md describes the contract and where the feed comes from.');
  process.exit(1);
}

let feed;
try { feed = JSON.parse(fs.readFileSync(src, 'utf8')); }
catch (e) { console.error(src + ' is not valid JSON: ' + e.message); process.exit(1); }

/* Colby terms include Jan Plan, which Hyperschedule's FA/SP/SU vocabulary has no
   room for. JA is added rather than folded into SP: a Jan Plan course is its own
   registration with its own capacity, and three of them are a graduation
   requirement, so the page must be able to tell them apart. */
const TERM = /^(FA|JA|SP|SU)[0-9]{4}$/;
const STATUS = new Set(['O', 'C', 'R', 'U']);
const CODE = /^([A-Z]{2,3}) ([0-9]{3}[A-Z]?)$/;

const need = (cond, msg) => { if (!cond) problems.push(msg); };

need(typeof feed.term === 'string' && TERM.test(feed.term),
     'term must look like FA2026, JA2027, SP2027 or SU2027, got ' + JSON.stringify(feed.term));
need(typeof feed.termName === 'string' && feed.termName.length > 0, 'termName must be a non-empty string');
need(typeof feed.fetchedAt === 'string' && !Number.isNaN(Date.parse(feed.fetchedAt)),
     'fetchedAt must be an ISO 8601 timestamp');
need(Array.isArray(feed.sections) && feed.sections.length > 0, 'sections must be a non-empty array');

if (problems.length) { report(); process.exit(1); }

const age = (Date.now() - Date.parse(feed.fetchedAt)) / 36e5;
if (age > 24) notes.push('feed is ' + age.toFixed(1) + ' hours old; the page will say so on screen');
if (age < -1) problems.push('fetchedAt is in the future');

const seen = new Map();
let over = 0;

feed.sections.forEach((s, i) => {
  const at = 'sections[' + i + ']';
  const code = normalise(s && s.code);
  if (!code) { problems.push(at + ': code ' + JSON.stringify(s && s.code) + ' does not resolve to a Colby course code'); return; }

  const total = s.seatsTotal, filled = s.seatsFilled;
  if (!Number.isInteger(total) || total < 0) { problems.push(at + ' ' + code + ': seatsTotal must be a non-negative integer'); return; }
  if (!Number.isInteger(filled) || filled < 0) { problems.push(at + ' ' + code + ': seatsFilled must be a non-negative integer'); return; }

  /* Over-enrolment is legal here and must not be rejected. An instructor who ticks
     "override Max Reg" on the course-authorisation page puts a student in past the
     cap on purpose, so 31/30 is a real state Colby can be in, not a broken export. */
  if (filled > total) over++;

  if (s.status !== undefined && !STATUS.has(s.status)) {
    problems.push(at + ' ' + code + ': status must be one of O, C, R, U (got ' + JSON.stringify(s.status) + ')');
  }

  const key = code + '|' + String(s.section || '');
  if (seen.has(key)) problems.push(at + ': ' + key + ' appears twice; sections must be unique per course');
  seen.set(key, true);
});

if (over) notes.push(over + ' section(s) enrolled past capacity, which an instructor authorisation can do legitimately');

function normalise(raw) {
  if (typeof raw !== 'string') return '';
  const m = raw.toUpperCase().replace(/[^A-Z0-9]/g, ' ').trim().match(/^([A-Z]{2,3}) *([0-9]{3}[A-Z]?)/);
  return m ? m[1] + ' ' + m[2] : '';
}

function report() {
  problems.slice(0, 40).forEach(p => console.error('  ' + p));
  if (problems.length > 40) console.error('  ... and ' + (problems.length - 40) + ' more');
}

if (problems.length) {
  console.error(problems.length + ' problem(s) in ' + src + ', nothing written:');
  report();
  process.exit(1);
}

const banner = [
  '/* ColbyMajorGuide: live seat data. Generated by build-seats.mjs, do not hand-edit.',
  ' *',
  ' * Source: ' + String(feed.source || 'unspecified'),
  ' * Term:   ' + feed.termName + ' (' + feed.term + ')',
  ' * Read:   ' + new Date(feed.fetchedAt).toISOString(),
  ' */',
  'window.CMG_SEATS = '
].join('\n');

fs.writeFileSync('seats.data.js', banner + JSON.stringify(feed, null, 1) + ';\n');

const courses = new Set([...seen.keys()].map(k => k.split('|')[0]));
console.log('seats.data.js written');
console.log('  ' + feed.termName + ' (' + feed.term + '), read ' + new Date(feed.fetchedAt).toISOString());
console.log('  ' + feed.sections.length + ' sections across ' + courses.size + ' courses');
notes.forEach(n => console.log('  note: ' + n));
console.log('\nok, feed is consistent');
