/* Generated by build-colby.mjs. Do not edit by hand.
 * A dated snapshot of Colby's own course search, not a live feed.
 */
window.CMG_SEATS = {
 "term": "FA2026",
 "termName": "Fall 2026",
 "termStart": "2026-09-09",
 "termEnd": "2026-12-21",
 "fetchedAt": "2026-08-28T00:00:00.000Z",
 "source": "Colby course search, captured by hand on 2026-08-28. A snapshot, not a live feed: it was true when it was taken and goes stale as students add and drop.",
 "snapshot": true,
 "sections": [
  {
   "code": "AA 120B",
   "section": "A",
   "title": "Critical Inquiries in Medical Ethics",
   "instructors": [
    "Jay Sibara"
   ],
   "seatsTotal": 16,
   "seatsFilled": 16,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "WF",
     "startTime": "14:30",
     "endTime": "15:45",
     "location": ""
    }
   ],
   "crossList": [
    "AA 120B-A",
    "WG 120B-A"
   ],
   "dept": "Women's, Gender, and Sexuality Studies"
  },
  {
   "code": "AA 120L",
   "section": "A",
   "title": "Language, Thought, and Writing: Language + Race + Power",
   "instructors": [
    "Sam Plasencia"
   ],
   "seatsTotal": 16,
   "seatsFilled": 14,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MW",
     "startTime": "13:00",
     "endTime": "14:15",
     "location": ""
    }
   ],
   "crossList": [
    "AA 120L-A",
    "EN 120L-A"
   ],
   "dept": "English"
  },
  {
   "code": "AA 124",
   "section": "A",
   "title": "Performance, Politics, and Practice",
   "instructors": [
    "Gwyneth Shanks"
   ],
   "seatsTotal": 20,
   "seatsFilled": 20,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "13:00",
     "endTime": "14:15",
     "location": ""
    }
   ],
   "crossList": [
    "AA 124-A",
    "TD 124-A"
   ],
   "dept": "Performance, Theater, and Dance"
  },
  {
   "code": "AA 125",
   "section": "A",
   "title": "Introduction to African American Cultures",
   "instructors": [
    "Sonya Donaldson"
   ],
   "seatsTotal": 30,
   "seatsFilled": 30,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "11:00",
     "endTime": "12:15",
     "location": ""
    }
   ],
   "crossList": [
    "AA 125-A",
    "AM 125-A"
   ],
   "dept": "African-American Studies"
  },
  {
   "code": "AA 162",
   "section": "A",
   "title": "History of the Atlantic World",
   "instructors": [
    "Kelly Brignac"
   ],
   "seatsTotal": 40,
   "seatsFilled": 40,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "13:00",
     "endTime": "14:15",
     "location": ""
    }
   ],
   "crossList": [
    "AA 162-A",
    "HI 162-A"
   ],
   "dept": "History"
  },
  {
   "code": "AA 171",
   "section": "A",
   "title": "Histories of the Present",
   "instructors": [
    "Ben Lisle"
   ],
   "seatsTotal": 25,
   "seatsFilled": 25,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "MW",
     "startTime": "11:00",
     "endTime": "12:15",
     "location": ""
    }
   ],
   "crossList": [
    "AA 171-A",
    "AM 171-A"
   ],
   "dept": "American Studies"
  },
  {
   "code": "AA 218",
   "section": "A",
   "title": "African American Migrations: Exiles, Expats, and Travelers",
   "instructors": [
    "Sonya Donaldson"
   ],
   "seatsTotal": 18,
   "seatsFilled": 18,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "W",
     "startTime": "13:00",
     "endTime": "15:30",
     "location": ""
    }
   ],
   "dept": "African-American Studies"
  },
  {
   "code": "AA 228",
   "section": "A",
   "title": "Introduction to Race, Ethnicity, and Politics",
   "instructors": [
    "Carrie LeVan"
   ],
   "seatsTotal": 25,
   "seatsFilled": 25,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "09:30",
     "endTime": "10:45",
     "location": ""
    }
   ],
   "crossList": [
    "AA 228-A",
    "GO 228-A"
   ],
   "dept": "Government"
  },
  {
   "code": "AA 247",
   "section": "A",
   "title": "African-American History, from Slavery to Freedom",
   "instructors": [
    "Rob Weisbrot"
   ],
   "seatsTotal": 30,
   "seatsFilled": 29,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MW",
     "startTime": "14:30",
     "endTime": "15:45",
     "location": ""
    }
   ],
   "crossList": [
    "AA 247-A",
    "HI 247-A"
   ],
   "dept": "History"
  },
  {
   "code": "AA 258",
   "section": "A",
   "title": "Anthropology, History, Memory",
   "instructors": [
    "Chandra Bhimull"
   ],
   "seatsTotal": 18,
   "seatsFilled": 16,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MW",
     "startTime": "11:00",
     "endTime": "12:15",
     "location": ""
    }
   ],
   "crossList": [
    "AA 258-A",
    "AY 258-A"
   ],
   "dept": "Anthropology"
  },
  {
   "code": "AA 267",
   "section": "A",
   "title": "Critical Perspectives on Sports and Societies",
   "instructors": [
    "Joshua Rubin"
   ],
   "seatsTotal": 18,
   "seatsFilled": 18,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "11:00",
     "endTime": "12:15",
     "location": ""
    }
   ],
   "crossList": [
    "AA 267-A",
    "AY 267-A"
   ],
   "dept": "Anthropology"
  },
  {
   "code": "AA 268",
   "section": "A",
   "title": "Afrofuturism and Social Justice",
   "instructors": [
    "Sonya Donaldson"
   ],
   "seatsTotal": 18,
   "seatsFilled": 15,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "13:00",
     "endTime": "14:15",
     "location": ""
    }
   ],
   "dept": "African-American Studies"
  },
  {
   "code": "AA 319",
   "section": "A",
   "title": "Art, Medicine, and Race",
   "instructors": [
    "Tanya Sheehan"
   ],
   "seatsTotal": 16,
   "seatsFilled": 15,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "F",
     "startTime": "13:00",
     "endTime": "15:30",
     "location": ""
    }
   ],
   "crossList": [
    "AA 319-A",
    "AM 319-A",
    "AR 319-A",
    "ST 319-A"
   ],
   "dept": "Art"
  },
  {
   "code": "AA 333",
   "section": "A",
   "title": "Contemporary Theory",
   "instructors": [
    "M. Suzanne Menair"
   ],
   "seatsTotal": 15,
   "seatsFilled": 9,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "W",
     "startTime": "13:00",
     "endTime": "15:30",
     "location": ""
    }
   ],
   "crossList": [
    "AA 333-A",
    "AY 333-A"
   ],
   "dept": "Anthropology"
  },
  {
   "code": "AA 334",
   "section": "A",
   "title": "The Great Depression: America in the 1930s",
   "instructors": [
    "Rob Weisbrot"
   ],
   "seatsTotal": 16,
   "seatsFilled": 16,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "T",
     "startTime": "19:00",
     "endTime": "21:30",
     "location": ""
    }
   ],
   "crossList": [
    "AA 334-A",
    "HI 334-A"
   ],
   "dept": "History"
  },
  {
   "code": "AA 341",
   "section": "A",
   "title": "Culture, Mobility, Identity: Encounters in the African Diaspora",
   "instructors": [
    "Chandra Bhimull"
   ],
   "seatsTotal": 15,
   "seatsFilled": 4,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "W",
     "startTime": "13:00",
     "endTime": "15:30",
     "location": ""
    }
   ],
   "crossList": [
    "AA 341-A",
    "AY 341-A"
   ],
   "dept": "Anthropology"
  },
  {
   "code": "AA 354",
   "section": "A",
   "title": "Surveillance Culture",
   "instructors": [
    "Amber Hickey"
   ],
   "seatsTotal": 15,
   "seatsFilled": 15,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "11:00",
     "endTime": "12:15",
     "location": ""
    }
   ],
   "crossList": [
    "AA 354-A",
    "AM 354-A",
    "WG 354-A"
   ],
   "dept": "American Studies"
  },
  {
   "code": "AA 393",
   "section": "A",
   "title": "Junior Seminar: Theories of Culture",
   "instructors": [
    "Amber Hickey"
   ],
   "seatsTotal": 15,
   "seatsFilled": 6,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "14:30",
     "endTime": "15:45",
     "location": ""
    }
   ],
   "crossList": [
    "AA 393-A",
    "AM 393-A"
   ],
   "dept": "American Studies"
  },
  {
   "code": "AI 297",
   "section": "A",
   "title": "Artificial Intelligence Lab",
   "instructors": [
    "David Watts"
   ],
   "seatsTotal": 10,
   "seatsFilled": 13,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 3,
   "schedule": [
    {
     "days": "R",
     "startTime": "19:00",
     "endTime": "21:00",
     "location": ""
    }
   ],
   "dept": "Colby College"
  },
  {
   "code": "AM 125",
   "section": "A",
   "title": "Introduction to African American Cultures",
   "instructors": [
    "Sonya Donaldson"
   ],
   "seatsTotal": 30,
   "seatsFilled": 30,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "11:00",
     "endTime": "12:15",
     "location": ""
    }
   ],
   "crossList": [
    "AA 125-A",
    "AM 125-A"
   ],
   "dept": "African-American Studies"
  },
  {
   "code": "AM 171",
   "section": "A",
   "title": "Histories of the Present",
   "instructors": [
    "Ben Lisle"
   ],
   "seatsTotal": 25,
   "seatsFilled": 25,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "MW",
     "startTime": "11:00",
     "endTime": "12:15",
     "location": ""
    }
   ],
   "crossList": [
    "AA 171-A",
    "AM 171-A"
   ],
   "dept": "American Studies"
  },
  {
   "code": "AM 232",
   "section": "A",
   "title": "Queer Identities and Politics",
   "instructors": [
    "Laura Sachiko Fugikawa"
   ],
   "seatsTotal": 16,
   "seatsFilled": 16,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "14:30",
     "endTime": "15:45",
     "location": ""
    }
   ],
   "crossList": [
    "AM 232-A",
    "WG 232-A"
   ],
   "dept": "Women's, Gender, and Sexuality Studies"
  },
  {
   "code": "AM 255",
   "section": "A",
   "title": "Sounding the Great Migration: 1900-1945",
   "instructors": [
    "Emmalouise St. Amand"
   ],
   "seatsTotal": 15,
   "seatsFilled": 12,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MW",
     "startTime": "14:30",
     "endTime": "15:45",
     "location": ""
    }
   ],
   "crossList": [
    "AM 255-A",
    "MU 255-A"
   ],
   "dept": "Music"
  },
  {
   "code": "AM 319",
   "section": "A",
   "title": "Art, Medicine, and Race",
   "instructors": [
    "Tanya Sheehan"
   ],
   "seatsTotal": 16,
   "seatsFilled": 15,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "F",
     "startTime": "13:00",
     "endTime": "15:30",
     "location": ""
    }
   ],
   "crossList": [
    "AA 319-A",
    "AM 319-A",
    "AR 319-A",
    "ST 319-A"
   ],
   "dept": "Art"
  },
  {
   "code": "AM 354",
   "section": "A",
   "title": "Surveillance Culture",
   "instructors": [
    "Amber Hickey"
   ],
   "seatsTotal": 15,
   "seatsFilled": 15,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "11:00",
     "endTime": "12:15",
     "location": ""
    }
   ],
   "crossList": [
    "AA 354-A",
    "AM 354-A",
    "WG 354-A"
   ],
   "dept": "American Studies"
  },
  {
   "code": "AM 366",
   "section": "A",
   "title": "Race, Gender, and the Graphic Novel",
   "instructors": [
    "Laura Sachiko Fugikawa"
   ],
   "seatsTotal": 16,
   "seatsFilled": 15,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "09:30",
     "endTime": "10:45",
     "location": ""
    }
   ],
   "crossList": [
    "AM 366-A",
    "WG 366-A"
   ],
   "dept": "American Studies"
  },
  {
   "code": "AM 393",
   "section": "A",
   "title": "Junior Seminar: Theories of Culture",
   "instructors": [
    "Amber Hickey"
   ],
   "seatsTotal": 15,
   "seatsFilled": 6,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "14:30",
     "endTime": "15:45",
     "location": ""
    }
   ],
   "crossList": [
    "AA 393-A",
    "AM 393-A"
   ],
   "dept": "American Studies"
  },
  {
   "code": "AR 111",
   "section": "A",
   "title": "Introduction to Western Art: Prehistory through the Middle Ages",
   "instructors": [
    "Véronique Plesch"
   ],
   "seatsTotal": 25,
   "seatsFilled": 25,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "MW",
     "startTime": "11:00",
     "endTime": "12:15",
     "location": ""
    }
   ],
   "dept": "Art"
  },
  {
   "code": "AR 125",
   "section": "A",
   "title": "Art and Architecture of the Islamic World, 622-1258",
   "instructors": [
    "Marta Ameri"
   ],
   "seatsTotal": 28,
   "seatsFilled": 28,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "11:00",
     "endTime": "12:15",
     "location": ""
    }
   ],
   "dept": "Art"
  },
  {
   "code": "AR 215",
   "section": "A",
   "title": "Art and Archaeology of the Ancient Near East and Egypt",
   "instructors": [
    "Marta Ameri"
   ],
   "seatsTotal": 28,
   "seatsFilled": 28,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "14:30",
     "endTime": "15:45",
     "location": ""
    }
   ],
   "crossList": [
    "AR 215-A",
    "CL 215-A"
   ],
   "dept": "Art"
  },
  {
   "code": "AR 221",
   "section": "A",
   "title": "Drawing I",
   "instructors": [
    "Luke Johnson"
   ],
   "seatsTotal": 15,
   "seatsFilled": 15,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "MW",
     "startTime": "09:00",
     "endTime": "10:50",
     "location": ""
    }
   ],
   "dept": "Art"
  },
  {
   "code": "AR 228",
   "section": "A",
   "title": "Printmaking I",
   "instructors": [
    "Amanda Lilleston"
   ],
   "seatsTotal": 15,
   "seatsFilled": 15,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "MW",
     "startTime": "14:00",
     "endTime": "15:50",
     "location": ""
    }
   ],
   "dept": "Art"
  },
  {
   "code": "AR 236",
   "section": "A",
   "title": "Vienna 1900",
   "instructors": [
    "Véronique Plesch"
   ],
   "seatsTotal": 24,
   "seatsFilled": 19,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MW",
     "startTime": "14:30",
     "endTime": "15:45",
     "location": ""
    }
   ],
   "crossList": [
    "AR 236-A",
    "GM 238-A",
    "JS 236-A"
   ],
   "dept": "Art"
  },
  {
   "code": "AR 240",
   "section": "A",
   "title": "Digital Media I: From Screen to Prints",
   "instructors": [
    "Taka Suzuki"
   ],
   "seatsTotal": 12,
   "seatsFilled": 12,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "MW",
     "startTime": "09:00",
     "endTime": "10:50",
     "location": ""
    }
   ],
   "dept": "Art"
  },
  {
   "code": "AR 241",
   "section": "A",
   "title": "Painting I",
   "instructors": [
    "Bevin Engman"
   ],
   "seatsTotal": 16,
   "seatsFilled": 16,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "14:00",
     "endTime": "15:50",
     "location": ""
    }
   ],
   "dept": "Art"
  },
  {
   "code": "AR 265",
   "section": "A",
   "title": "Sculpture I: Dynamic Wood",
   "instructors": [
    "Audrey Shakespear"
   ],
   "seatsTotal": 16,
   "seatsFilled": 16,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "MW",
     "startTime": "11:00",
     "endTime": "12:50",
     "location": ""
    }
   ],
   "dept": "Art"
  },
  {
   "code": "AR 266",
   "section": "A",
   "title": "Sculpture II: The Artifact",
   "instructors": [
    "Audrey Shakespear"
   ],
   "seatsTotal": 8,
   "seatsFilled": 2,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MW",
     "startTime": "14:00",
     "endTime": "15:50",
     "location": ""
    }
   ],
   "dept": "Art"
  },
  {
   "code": "AR 267",
   "section": "A",
   "title": "Advanced Topics in Design: Architectural Imaging",
   "instructors": [
    "Jim Thurston"
   ],
   "seatsTotal": 12,
   "seatsFilled": 11,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MW",
     "startTime": "14:30",
     "endTime": "16:00",
     "location": ""
    }
   ],
   "crossList": [
    "AR 267-A",
    "TD 365-A"
   ],
   "dept": "Performance, Theater, and Dance"
  },
  {
   "code": "AR 278",
   "section": "A",
   "title": "19th-Century European Art",
   "instructors": [
    "Daniel Harkett"
   ],
   "seatsTotal": 25,
   "seatsFilled": 24,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "13:00",
     "endTime": "14:15",
     "location": ""
    }
   ],
   "dept": "Art"
  },
  {
   "code": "AR 281",
   "section": "A",
   "title": "Photography I",
   "instructors": [
    "Alex Nelson"
   ],
   "seatsTotal": 15,
   "seatsFilled": 15,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "11:00",
     "endTime": "12:50",
     "location": ""
    }
   ],
   "dept": "Art"
  },
  {
   "code": "AR 319",
   "section": "A",
   "title": "Art, Medicine, and Race",
   "instructors": [
    "Tanya Sheehan"
   ],
   "seatsTotal": 16,
   "seatsFilled": 15,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "F",
     "startTime": "13:00",
     "endTime": "15:30",
     "location": ""
    }
   ],
   "crossList": [
    "AA 319-A",
    "AM 319-A",
    "AR 319-A",
    "ST 319-A"
   ],
   "dept": "Art"
  },
  {
   "code": "AR 328",
   "section": "A",
   "title": "Printmaking III",
   "instructors": [
    "Amanda Lilleston"
   ],
   "seatsTotal": 15,
   "seatsFilled": 1,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MW",
     "startTime": "11:00",
     "endTime": "12:50",
     "location": ""
    }
   ],
   "dept": "Art"
  },
  {
   "code": "AR 340",
   "section": "A",
   "title": "Art and Activism in Contemporary Cuba",
   "instructors": [
    "Brett White"
   ],
   "seatsTotal": 15,
   "seatsFilled": 7,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "14:30",
     "endTime": "15:45",
     "location": ""
    }
   ],
   "crossList": [
    "AR 340-A",
    "LA 340-A",
    "SP 340-A",
    "TD 340-A"
   ],
   "dept": "Spanish"
  },
  {
   "code": "AR 341",
   "section": "A",
   "title": "Painting III",
   "instructors": [
    "Bevin Engman"
   ],
   "seatsTotal": 16,
   "seatsFilled": 7,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "11:00",
     "endTime": "12:50",
     "location": ""
    }
   ],
   "dept": "Art"
  },
  {
   "code": "AR 342",
   "section": "A",
   "title": "Painting IV",
   "instructors": [
    "Bevin Engman"
   ],
   "seatsTotal": 16,
   "seatsFilled": 0,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "11:00",
     "endTime": "12:50",
     "location": ""
    }
   ],
   "dept": "Art"
  },
  {
   "code": "AR 360",
   "section": "A",
   "title": "Digital Media III: Sound as Art",
   "instructors": [
    "Taka Suzuki"
   ],
   "seatsTotal": 12,
   "seatsFilled": 9,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "09:00",
     "endTime": "10:50",
     "location": ""
    }
   ],
   "dept": "Art"
  },
  {
   "code": "AR 381",
   "section": "A",
   "title": "Photography III: Color and Digital Photography",
   "instructors": [
    "Alex Nelson"
   ],
   "seatsTotal": 12,
   "seatsFilled": 3,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "14:00",
     "endTime": "15:50",
     "location": ""
    }
   ],
   "dept": "Art"
  },
  {
   "code": "AR 382",
   "section": "A",
   "title": "Photography IV",
   "instructors": [
    "Alex Nelson"
   ],
   "seatsTotal": 12,
   "seatsFilled": 0,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "14:00",
     "endTime": "15:50",
     "location": ""
    }
   ],
   "dept": "Art"
  },
  {
   "code": "AR 401",
   "section": "A",
   "title": "Studio Art Capstone",
   "instructors": [
    "Taka Suzuki"
   ],
   "seatsTotal": 20,
   "seatsFilled": 12,
   "status": "O",
   "rawStatus": "Open",
   "credits": 2,
   "schedule": [
    {
     "days": "F",
     "startTime": "10:00",
     "endTime": "12:30",
     "location": ""
    }
   ],
   "dept": "Art"
  },
  {
   "code": "AR 428",
   "section": "A",
   "title": "Printmaking V",
   "instructors": [
    "Amanda Lilleston"
   ],
   "seatsTotal": 15,
   "seatsFilled": 2,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MW",
     "startTime": "11:00",
     "endTime": "12:50",
     "location": ""
    }
   ],
   "dept": "Art"
  },
  {
   "code": "AR 438",
   "section": "A",
   "title": "Printmaking VII",
   "instructors": [
    "Amanda Lilleston"
   ],
   "seatsTotal": 15,
   "seatsFilled": 0,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MW",
     "startTime": "11:00",
     "endTime": "12:50",
     "location": ""
    }
   ],
   "dept": "Art"
  },
  {
   "code": "AR 441",
   "section": "A",
   "title": "Painting V",
   "instructors": [
    "Bevin Engman"
   ],
   "seatsTotal": 16,
   "seatsFilled": 3,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "11:00",
     "endTime": "12:50",
     "location": ""
    }
   ],
   "dept": "Art"
  },
  {
   "code": "AR 442",
   "section": "A",
   "title": "Painting VI",
   "instructors": [
    "Bevin Engman"
   ],
   "seatsTotal": 16,
   "seatsFilled": 1,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "11:00",
     "endTime": "12:50",
     "location": ""
    }
   ],
   "dept": "Art"
  },
  {
   "code": "AR 443",
   "section": "A",
   "title": "Painting VII",
   "instructors": [
    "Bevin Engman"
   ],
   "seatsTotal": 16,
   "seatsFilled": 0,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "11:00",
     "endTime": "12:50",
     "location": ""
    }
   ],
   "dept": "Art"
  },
  {
   "code": "AR 450",
   "section": "A",
   "title": "Digital Media Advanced Studio I",
   "instructors": [
    "Taka Suzuki"
   ],
   "seatsTotal": 12,
   "seatsFilled": 1,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "09:00",
     "endTime": "10:50",
     "location": ""
    }
   ],
   "dept": "Art"
  },
  {
   "code": "AR 460",
   "section": "A",
   "title": "Digital Media Advanced Studio II",
   "instructors": [
    "Taka Suzuki"
   ],
   "seatsTotal": 12,
   "seatsFilled": 0,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "09:00",
     "endTime": "10:50",
     "location": ""
    }
   ],
   "dept": "Art"
  },
  {
   "code": "AR 465",
   "section": "A",
   "title": "Sculpture V",
   "instructors": [
    "Audrey Shakespear"
   ],
   "seatsTotal": 6,
   "seatsFilled": 1,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MW",
     "startTime": "14:00",
     "endTime": "15:50",
     "location": ""
    }
   ],
   "dept": "Art"
  },
  {
   "code": "AR 481",
   "section": "A",
   "title": "Photography V",
   "instructors": [
    "Alex Nelson"
   ],
   "seatsTotal": 12,
   "seatsFilled": 2,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "14:00",
     "endTime": "15:50",
     "location": ""
    }
   ],
   "dept": "Art"
  },
  {
   "code": "AR 482",
   "section": "A",
   "title": "Photography VI",
   "instructors": [
    "Alex Nelson"
   ],
   "seatsTotal": 12,
   "seatsFilled": 0,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "14:00",
     "endTime": "15:50",
     "location": ""
    }
   ],
   "dept": "Art"
  },
  {
   "code": "AR 485",
   "section": "A",
   "title": "Photography VII",
   "instructors": [
    "Alex Nelson"
   ],
   "seatsTotal": 12,
   "seatsFilled": 0,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "14:00",
     "endTime": "15:50",
     "location": ""
    }
   ],
   "dept": "Art"
  },
  {
   "code": "AR 494",
   "section": "A",
   "title": "Senior Research Seminar in Art History",
   "instructors": [
    "Marta Ameri"
   ],
   "seatsTotal": 12,
   "seatsFilled": 7,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "W",
     "startTime": "13:00",
     "endTime": "15:30",
     "location": ""
    }
   ],
   "dept": "Art"
  },
  {
   "code": "AS 231",
   "section": "A",
   "title": "Introduction to Astrophysics",
   "instructors": [
    "Elizabeth McGrath"
   ],
   "seatsTotal": 18,
   "seatsFilled": 18,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "10:00",
     "endTime": "10:50",
     "location": ""
    }
   ],
   "partialSchedule": true,
   "dept": "Physics and Astronomy"
  },
  {
   "code": "AY 112",
   "section": "A",
   "title": "Cultural Anthropology",
   "instructors": [
    "M. Suzanne Menair"
   ],
   "seatsTotal": 32,
   "seatsFilled": 32,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "09:30",
     "endTime": "10:45",
     "location": ""
    }
   ],
   "dept": "Anthropology"
  },
  {
   "code": "AY 112",
   "section": "B",
   "title": "Cultural Anthropology",
   "instructors": [
    "Farah Qureshi"
   ],
   "seatsTotal": 30,
   "seatsFilled": 30,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "11:00",
     "endTime": "12:15",
     "location": ""
    }
   ],
   "dept": "Anthropology"
  },
  {
   "code": "AY 112",
   "section": "C",
   "title": "Cultural Anthropology",
   "instructors": [
    "Mehrdad Babadi"
   ],
   "seatsTotal": 30,
   "seatsFilled": 30,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "MW",
     "startTime": "11:00",
     "endTime": "12:15",
     "location": ""
    }
   ],
   "dept": "Anthropology"
  },
  {
   "code": "AY 200",
   "section": "A",
   "title": "Digital Infrastructure and Development",
   "instructors": [
    "Farah Qureshi"
   ],
   "seatsTotal": 18,
   "seatsFilled": 18,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "13:00",
     "endTime": "14:15",
     "location": ""
    }
   ],
   "crossList": [
    "AY 200-A",
    "ST 200-A"
   ],
   "dept": "Anthropology"
  },
  {
   "code": "AY 212A",
   "section": "A",
   "title": "Feeling, Sensing, Thinking in Catastrophic Times",
   "instructors": [
    "Tanzeen R. Doha"
   ],
   "seatsTotal": 20,
   "seatsFilled": 19,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "09:30",
     "endTime": "10:45",
     "location": ""
    }
   ],
   "crossList": [
    "AY 212A-A",
    "GS 212-A"
   ],
   "dept": "Global Studies"
  },
  {
   "code": "AY 213A",
   "section": "A",
   "title": "Constructing the Enemy: Race, Religion and Globalization",
   "instructors": [
    "Tanzeen R. Doha"
   ],
   "seatsTotal": 20,
   "seatsFilled": 20,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "13:00",
     "endTime": "14:15",
     "location": ""
    }
   ],
   "crossList": [
    "AY 213A-A",
    "GS 213-A"
   ],
   "dept": "Global Studies"
  },
  {
   "code": "AY 250",
   "section": "A",
   "title": "Introduction to World Music",
   "instructors": [
    "Natalie Zelensky"
   ],
   "seatsTotal": 25,
   "seatsFilled": 25,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "13:00",
     "endTime": "14:15",
     "location": ""
    }
   ],
   "crossList": [
    "AY 250-A",
    "MU 252-A"
   ],
   "dept": "Music"
  },
  {
   "code": "AY 258",
   "section": "A",
   "title": "Anthropology, History, Memory",
   "instructors": [
    "Chandra Bhimull"
   ],
   "seatsTotal": 18,
   "seatsFilled": 16,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MW",
     "startTime": "11:00",
     "endTime": "12:15",
     "location": ""
    }
   ],
   "crossList": [
    "AA 258-A",
    "AY 258-A"
   ],
   "dept": "Anthropology"
  },
  {
   "code": "AY 260",
   "section": "A",
   "title": "Love and Intimacy in the Middle East",
   "instructors": [
    "Mehrdad Babadi"
   ],
   "seatsTotal": 18,
   "seatsFilled": 11,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MW",
     "startTime": "14:30",
     "endTime": "15:45",
     "location": ""
    }
   ],
   "dept": "Anthropology"
  },
  {
   "code": "AY 262",
   "section": "A",
   "title": "Music in Life, Music as Culture: Introduction to Ethnomusicology",
   "instructors": [
    "Natalie Zelensky"
   ],
   "seatsTotal": 12,
   "seatsFilled": 12,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "09:30",
     "endTime": "10:45",
     "location": ""
    }
   ],
   "crossList": [
    "AY 262-A",
    "MU 262-A"
   ],
   "dept": "Music"
  },
  {
   "code": "AY 266",
   "section": "A",
   "title": "Pixelated Parts: Race, Gender, Video Games",
   "instructors": [
    "Joshua Rubin"
   ],
   "seatsTotal": 18,
   "seatsFilled": 5,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "14:30",
     "endTime": "15:45",
     "location": ""
    }
   ],
   "dept": "Anthropology"
  },
  {
   "code": "AY 267",
   "section": "A",
   "title": "Critical Perspectives on Sports and Societies",
   "instructors": [
    "Joshua Rubin"
   ],
   "seatsTotal": 18,
   "seatsFilled": 18,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "11:00",
     "endTime": "12:15",
     "location": ""
    }
   ],
   "crossList": [
    "AA 267-A",
    "AY 267-A"
   ],
   "dept": "Anthropology"
  },
  {
   "code": "AY 313",
   "section": "A",
   "title": "Researching Cultural Diversity",
   "instructors": [
    "Britt Halvorson"
   ],
   "seatsTotal": 15,
   "seatsFilled": 12,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "R",
     "startTime": "13:00",
     "endTime": "15:30",
     "location": ""
    }
   ],
   "crossList": [
    "AY 313-A",
    "GS 313-A"
   ],
   "dept": "Anthropology"
  },
  {
   "code": "AY 325",
   "section": "A",
   "title": "Art, Power, and Politics",
   "instructors": [
    "Joshua Rubin"
   ],
   "seatsTotal": 15,
   "seatsFilled": 15,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "M",
     "startTime": "13:00",
     "endTime": "15:30",
     "location": ""
    }
   ],
   "dept": "Anthropology"
  },
  {
   "code": "AY 333",
   "section": "A",
   "title": "Contemporary Theory",
   "instructors": [
    "M. Suzanne Menair"
   ],
   "seatsTotal": 15,
   "seatsFilled": 9,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "W",
     "startTime": "13:00",
     "endTime": "15:30",
     "location": ""
    }
   ],
   "crossList": [
    "AA 333-A",
    "AY 333-A"
   ],
   "dept": "Anthropology"
  },
  {
   "code": "AY 341",
   "section": "A",
   "title": "Culture, Mobility, Identity: Encounters in the African Diaspora",
   "instructors": [
    "Chandra Bhimull"
   ],
   "seatsTotal": 15,
   "seatsFilled": 4,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "W",
     "startTime": "13:00",
     "endTime": "15:30",
     "location": ""
    }
   ],
   "crossList": [
    "AA 341-A",
    "AY 341-A"
   ],
   "dept": "Anthropology"
  },
  {
   "code": "AY 352",
   "section": "A",
   "title": "Liberation Struggles",
   "instructors": [
    "Maple Razsa"
   ],
   "seatsTotal": 15,
   "seatsFilled": 14,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "W",
     "startTime": "13:00",
     "endTime": "15:30",
     "location": ""
    }
   ],
   "crossList": [
    "AY 352-A",
    "GS 352-A"
   ],
   "dept": "Global Studies"
  },
  {
   "code": "BC 362",
   "section": "A",
   "title": "Medical Biochemistry",
   "instructors": [
    "Julie Millard"
   ],
   "seatsTotal": 24,
   "seatsFilled": 24,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "09:00",
     "endTime": "09:50",
     "location": ""
    }
   ],
   "crossList": [
    "BC 362-A",
    "BI 362-A",
    "CH 362-A"
   ],
   "dept": "Colby College"
  },
  {
   "code": "BC 367",
   "section": "A",
   "title": "Biochemistry of the Cell I",
   "instructors": [
    "Benedikt Blossom"
   ],
   "seatsTotal": 24,
   "seatsFilled": 24,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "10:00",
     "endTime": "10:50",
     "location": ""
    }
   ],
   "partialSchedule": true,
   "crossList": [
    "BC 367-A",
    "BI 367-A",
    "CH 367-A"
   ],
   "dept": "Colby College"
  },
  {
   "code": "BC 367",
   "section": "B",
   "title": "Biochemistry of the Cell I",
   "instructors": [
    "Robert Augustine"
   ],
   "seatsTotal": 24,
   "seatsFilled": 20,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "09:30",
     "endTime": "10:45",
     "location": ""
    }
   ],
   "partialSchedule": true,
   "crossList": [
    "BC 367-B",
    "BI 367-B",
    "CH 367-B"
   ],
   "dept": "Colby College"
  },
  {
   "code": "BC 367 L",
   "section": "A",
   "title": "Lab: Cell Biochemistry I",
   "instructors": [],
   "seatsTotal": 12,
   "seatsFilled": 12,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 1,
   "schedule": [
    {
     "days": "T",
     "startTime": "13:00",
     "endTime": "17:00",
     "location": ""
    }
   ],
   "crossList": [
    "BC 367 L-A",
    "BI 367 L-A",
    "CH 367 L-A"
   ],
   "dept": "Colby College"
  },
  {
   "code": "BC 367 L",
   "section": "B",
   "title": "Lab: Cell Biochemistry I",
   "instructors": [],
   "seatsTotal": 12,
   "seatsFilled": 12,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 1,
   "schedule": [
    {
     "days": "W",
     "startTime": "13:00",
     "endTime": "17:00",
     "location": ""
    }
   ],
   "crossList": [
    "BC 367 L-B",
    "BI 367 L-B",
    "CH 367 L-B"
   ],
   "dept": "Colby College"
  },
  {
   "code": "BC 367 L",
   "section": "C",
   "title": "Lab: Cell Biochemistry I",
   "instructors": [],
   "seatsTotal": 12,
   "seatsFilled": 12,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 1,
   "schedule": [
    {
     "days": "R",
     "startTime": "13:00",
     "endTime": "17:00",
     "location": ""
    }
   ],
   "crossList": [
    "BC 367 L-C",
    "BI 367 L-C",
    "CH 367 L-C"
   ],
   "dept": "Colby College"
  },
  {
   "code": "BI 100",
   "section": "A",
   "title": "Navigating the World of STEM Research",
   "instructors": [
    "Andrea Tilden"
   ],
   "seatsTotal": 20,
   "seatsFilled": 20,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 1,
   "schedule": [
    {
     "days": "F",
     "startTime": "13:00",
     "endTime": "13:50",
     "location": ""
    }
   ],
   "dept": "Biology"
  },
  {
   "code": "BI 106",
   "section": "A",
   "title": "Introduction to Epidemiology",
   "instructors": [
    "Jim Scott"
   ],
   "seatsTotal": 28,
   "seatsFilled": 26,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "10:00",
     "endTime": "10:50",
     "location": ""
    }
   ],
   "crossList": [
    "BI 106-A",
    "SC 106-A"
   ],
   "dept": "Statistics"
  },
  {
   "code": "BI 118",
   "section": "A",
   "title": "Sustainable Agriculture and Food Systems",
   "instructors": [
    "Andrew Marshall"
   ],
   "seatsTotal": 45,
   "seatsFilled": 45,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 3,
   "schedule": [
    {
     "days": "TR",
     "startTime": "11:00",
     "endTime": "12:15",
     "location": ""
    }
   ],
   "dept": "Biology"
  },
  {
   "code": "BI 118",
   "section": "B",
   "title": "Sustainable Agriculture and Food Systems",
   "instructors": [
    "Andrew Marshall"
   ],
   "seatsTotal": 46,
   "seatsFilled": 46,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 3,
   "schedule": [
    {
     "days": "TR",
     "startTime": "13:00",
     "endTime": "14:15",
     "location": ""
    }
   ],
   "dept": "Biology"
  },
  {
   "code": "BI 124",
   "section": "A",
   "title": "Unraveling the Answers to Beautiful Biological Questions",
   "instructors": [
    "Carol Hurney"
   ],
   "seatsTotal": 36,
   "seatsFilled": 15,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "14:30",
     "endTime": "15:45",
     "location": ""
    }
   ],
   "dept": "Biology"
  },
  {
   "code": "BI 142",
   "section": "A",
   "title": "Cancer: From the Clinic to the Lab and Back",
   "instructors": [
    "Johanna van Oers"
   ],
   "seatsTotal": 30,
   "seatsFilled": 30,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "09:00",
     "endTime": "09:50",
     "location": ""
    }
   ],
   "dept": "Biology"
  },
  {
   "code": "BI 142",
   "section": "B",
   "title": "Cancer: From the Clinic to the Lab and Back",
   "instructors": [
    "Johanna van Oers"
   ],
   "seatsTotal": 30,
   "seatsFilled": 30,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "11:00",
     "endTime": "11:50",
     "location": ""
    }
   ],
   "dept": "Biology"
  },
  {
   "code": "BI 163",
   "section": "A",
   "title": "The Cellular Basis of Life",
   "instructors": [
    "Russell Johnson"
   ],
   "seatsTotal": 57,
   "seatsFilled": 54,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "09:00",
     "endTime": "09:50",
     "location": ""
    }
   ],
   "dept": "Biology"
  },
  {
   "code": "BI 163",
   "section": "B",
   "title": "The Cellular Basis of Life",
   "instructors": [
    "Christina Cota"
   ],
   "seatsTotal": 57,
   "seatsFilled": 55,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "10:00",
     "endTime": "10:50",
     "location": ""
    }
   ],
   "dept": "Biology"
  },
  {
   "code": "BI 163",
   "section": "C",
   "title": "The Cellular Basis of Life",
   "instructors": [
    "Robert Augustine"
   ],
   "seatsTotal": 57,
   "seatsFilled": 55,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "11:00",
     "endTime": "11:50",
     "location": ""
    }
   ],
   "dept": "Biology"
  },
  {
   "code": "BI 163",
   "section": "D",
   "title": "The Cellular Basis of Life",
   "instructors": [
    "Yee Mon Thu"
   ],
   "seatsTotal": 57,
   "seatsFilled": 52,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "12:00",
     "endTime": "12:50",
     "location": ""
    }
   ],
   "dept": "Biology"
  },
  {
   "code": "BI 201",
   "section": "A",
   "title": "Biology Accelerator",
   "instructors": [
    "Catherine Bevier"
   ],
   "seatsTotal": 16,
   "seatsFilled": 14,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "11:00",
     "endTime": "11:50",
     "location": ""
    }
   ],
   "dept": "Biology"
  },
  {
   "code": "BI 211",
   "section": "A",
   "title": "Taxonomy of Flowering Plants",
   "instructors": [
    "Kristen Nolting"
   ],
   "seatsTotal": 32,
   "seatsFilled": 29,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "10:00",
     "endTime": "10:50",
     "location": ""
    }
   ],
   "crossList": [
    "BI 211-A",
    "ES 211-A"
   ],
   "dept": "Biology"
  },
  {
   "code": "BI 218",
   "section": "A",
   "title": "Evolutionary Cell Biology",
   "instructors": [
    "John Burns"
   ],
   "seatsTotal": 15,
   "seatsFilled": 15,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 3,
   "schedule": [
    {
     "days": "TR",
     "startTime": "11:00",
     "endTime": "12:15",
     "location": ""
    }
   ],
   "dept": "Biology"
  },
  {
   "code": "BI 225",
   "section": "A",
   "title": "Immunology",
   "instructors": [
    "Andrea Wegrzynowicz"
   ],
   "seatsTotal": 32,
   "seatsFilled": 32,
   "status": "C",
   "rawStatus": "Closed",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "10:00",
     "endTime": "10:50",
     "location": ""
    }
   ],
   "dept": "Biology"
  },
  {
   "code": "BI 230",
   "section": "A",
   "title": "Food: Biochemistry to Biopolitics",
   "instructors": [
    "Thom Klepach"
   ],
   "seatsTotal": 24,
   "seatsFilled": 14,
   "status": "O",
   "rawStatus": "Open",
   "credits": 3,
   "schedule": [
    {
     "days": "TR",
     "startTime": "09:30",
     "endTime": "10:45",
     "location": ""
    }
   ],
   "crossList": [
    "BI 230-A",
    "ST 230-A"
   ],
   "dept": "Science, Technology and Society"
  },
  {
   "code": "BI 241",
   "section": "A",
   "title": "Entomology",
   "instructors": [
    "Suegene Noh"
   ],
   "seatsTotal": 16,
   "seatsFilled": 15,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "09:00",
     "endTime": "09:50",
     "location": ""
    }
   ],
   "dept": "Biology"
  },
  {
   "code": "BI 244",
   "section": "A",
   "title": "Marine Communities",
   "instructors": [
    "Nick Funnell"
   ],
   "seatsTotal": 22,
   "seatsFilled": 19,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "11:00",
     "endTime": "12:15",
     "location": ""
    }
   ],
   "crossList": [
    "BI 244-A",
    "ES 244-A"
   ],
   "dept": "Environmental Studies"
  },
  {
   "code": "BI 248",
   "section": "A",
   "title": "Microbiology",
   "instructors": [
    "Ron Peck"
   ],
   "seatsTotal": 36,
   "seatsFilled": 36,
   "status": "C",
   "rawStatus": "Closed",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "09:30",
     "endTime": "10:45",
     "location": ""
    }
   ],
   "dept": "Biology"
  },
  {
   "code": "BI 254",
   "section": "A",
   "title": "Marine Biology of Coastal Maine",
   "instructors": [
    "Allison Barner"
   ],
   "seatsTotal": 12,
   "seatsFilled": 8,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "11:00",
     "endTime": "12:15",
     "location": ""
    }
   ],
   "crossList": [
    "BI 254-A",
    "ES 255-A"
   ],
   "dept": "Biology"
  },
  {
   "code": "BI 271",
   "section": "A",
   "title": "Ecology",
   "instructors": [
    "Amanda Gallinat"
   ],
   "seatsTotal": 36,
   "seatsFilled": 31,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "09:00",
     "endTime": "09:50",
     "location": ""
    }
   ],
   "crossList": [
    "BI 271-A",
    "ES 271-A"
   ],
   "dept": "Biology"
  },
  {
   "code": "BI 271",
   "section": "B",
   "title": "Ecology",
   "instructors": [
    "Kyle Coblentz"
   ],
   "seatsTotal": 36,
   "seatsFilled": 29,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "10:00",
     "endTime": "10:50",
     "location": ""
    }
   ],
   "crossList": [
    "BI 271-B",
    "ES 271-B"
   ],
   "dept": "Biology"
  },
  {
   "code": "BI 274",
   "section": "A",
   "title": "Neurobiology",
   "instructors": [
    "Josh Martin"
   ],
   "seatsTotal": 36,
   "seatsFilled": 36,
   "status": "C",
   "rawStatus": "Closed",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "11:00",
     "endTime": "11:50",
     "location": ""
    }
   ],
   "dept": "Biology"
  },
  {
   "code": "BI 277",
   "section": "A",
   "title": "Vertebrate Natural History",
   "instructors": [
    "Catherine Bevier"
   ],
   "seatsTotal": 24,
   "seatsFilled": 17,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "09:00",
     "endTime": "09:50",
     "location": ""
    }
   ],
   "dept": "Biology"
  },
  {
   "code": "BI 279",
   "section": "A",
   "title": "Genetics",
   "instructors": [
    "Dave Angelini"
   ],
   "seatsTotal": 24,
   "seatsFilled": 24,
   "status": "C",
   "rawStatus": "Closed",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "11:00",
     "endTime": "11:50",
     "location": ""
    }
   ],
   "dept": "Biology"
  },
  {
   "code": "BI 319",
   "section": "A",
   "title": "Conservation Biology",
   "instructors": [
    "Philip Nyhus"
   ],
   "seatsTotal": 36,
   "seatsFilled": 30,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "10:00",
     "endTime": "10:50",
     "location": ""
    }
   ],
   "crossList": [
    "BI 319-A",
    "ES 319-A"
   ],
   "dept": "Environmental Studies"
  },
  {
   "code": "BI 344",
   "section": "A",
   "title": "Microbiomes in Health and Disease",
   "instructors": [
    "Susan Childers"
   ],
   "seatsTotal": 16,
   "seatsFilled": 10,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "11:00",
     "endTime": "12:15",
     "location": ""
    }
   ],
   "dept": "Biology"
  },
  {
   "code": "BI 374",
   "section": "A",
   "title": "Advanced Neurobiology",
   "instructors": [
    "Josh Martin"
   ],
   "seatsTotal": 20,
   "seatsFilled": 15,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "09:30",
     "endTime": "10:45",
     "location": ""
    }
   ],
   "dept": "Biology"
  },
  {
   "code": "BI 392",
   "section": "A",
   "title": "Cell Biology of Cancer",
   "instructors": [
    "Christina Cota"
   ],
   "seatsTotal": 16,
   "seatsFilled": 9,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "11:00",
     "endTime": "12:15",
     "location": ""
    }
   ],
   "dept": "Biology"
  },
  {
   "code": "BI 397",
   "section": "A",
   "title": "Introduction to Hematology",
   "instructors": [
    "David Bodine"
   ],
   "seatsTotal": 18,
   "seatsFilled": 18,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "09:00",
     "endTime": "09:50",
     "location": ""
    }
   ],
   "dept": "Biology"
  },
  {
   "code": "CH 121",
   "section": "A",
   "title": "Earth Systems Chemistry I",
   "instructors": [
    "Karena McKinney"
   ],
   "seatsTotal": 32,
   "seatsFilled": 32,
   "status": "C",
   "rawStatus": "Closed",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "10:00",
     "endTime": "10:50",
     "location": ""
    }
   ],
   "crossList": [
    "CH 121-A",
    "ER 121-A"
   ],
   "dept": "Chemistry"
  },
  {
   "code": "CH 141",
   "section": "A",
   "title": "General Chemistry I",
   "instructors": [
    "Lindsey Madison"
   ],
   "seatsTotal": 72,
   "seatsFilled": 71,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "09:00",
     "endTime": "09:50",
     "location": ""
    }
   ],
   "dept": "Chemistry"
  },
  {
   "code": "CH 141",
   "section": "B",
   "title": "General Chemistry I",
   "instructors": [
    "Reuben Hudson"
   ],
   "seatsTotal": 72,
   "seatsFilled": 69,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "10:00",
     "endTime": "10:50",
     "location": ""
    }
   ],
   "dept": "Chemistry"
  },
  {
   "code": "CH 147",
   "section": "A",
   "title": "Comprehensive General Chemistry",
   "instructors": [
    "Whitney King"
   ],
   "seatsTotal": 32,
   "seatsFilled": 31,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "10:00",
     "endTime": "10:50",
     "location": ""
    }
   ],
   "dept": "Chemistry"
  },
  {
   "code": "CH 241",
   "section": "A",
   "title": "Organic Chemistry I",
   "instructors": [
    "Dasan Thamattoor"
   ],
   "seatsTotal": 56,
   "seatsFilled": 56,
   "status": "C",
   "rawStatus": "Closed",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "09:00",
     "endTime": "09:50",
     "location": ""
    }
   ],
   "dept": "Chemistry"
  },
  {
   "code": "CH 241",
   "section": "B",
   "title": "Organic Chemistry I",
   "instructors": [
    "Dasan Thamattoor"
   ],
   "seatsTotal": 56,
   "seatsFilled": 55,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "10:00",
     "endTime": "10:50",
     "location": ""
    }
   ],
   "dept": "Chemistry"
  },
  {
   "code": "CH 263",
   "section": "A",
   "title": "Atmospheric Chemistry",
   "instructors": [
    "Karena McKinney"
   ],
   "seatsTotal": 24,
   "seatsFilled": 10,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "12:00",
     "endTime": "12:50",
     "location": ""
    }
   ],
   "crossList": [
    "CH 263-A",
    "ES 263-A"
   ],
   "dept": "Chemistry"
  },
  {
   "code": "CH 341",
   "section": "A",
   "title": "Physical Chemistry: Thermodynamics and Kinetics",
   "instructors": [
    "Greg Drozd"
   ],
   "seatsTotal": 24,
   "seatsFilled": 20,
   "status": "O",
   "rawStatus": "Open",
   "credits": 5,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "11:00",
     "endTime": "11:50",
     "location": ""
    }
   ],
   "partialSchedule": true,
   "dept": "Chemistry"
  },
  {
   "code": "CH 432",
   "section": "A",
   "title": "Advanced Organic Chemistry",
   "instructors": [
    "Jeff Katz"
   ],
   "seatsTotal": 16,
   "seatsFilled": 11,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "09:30",
     "endTime": "10:45",
     "location": ""
    }
   ],
   "dept": "Chemistry"
  },
  {
   "code": "CH 493",
   "section": "A",
   "title": "Senior Seminar",
   "instructors": [
    "Lindsey Madison"
   ],
   "seatsTotal": 30,
   "seatsFilled": 13,
   "status": "O",
   "rawStatus": "Open",
   "credits": 1,
   "schedule": [
    {
     "days": "F",
     "startTime": "15:00",
     "endTime": "15:50",
     "location": ""
    }
   ],
   "dept": "Chemistry"
  },
  {
   "code": "CS 151",
   "section": "A",
   "title": "Computational Thinking: Visual Media",
   "instructors": [
    "Hannen Wolfe"
   ],
   "seatsTotal": 24,
   "seatsFilled": 22,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "09:00",
     "endTime": "09:50",
     "location": ""
    }
   ],
   "partialSchedule": true,
   "dept": "Computer Science"
  },
  {
   "code": "CS 151",
   "section": "B",
   "title": "Computational Thinking: Visual Media",
   "instructors": [
    "Hannen Wolfe"
   ],
   "seatsTotal": 24,
   "seatsFilled": 23,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "10:00",
     "endTime": "10:50",
     "location": ""
    }
   ],
   "partialSchedule": true,
   "dept": "Computer Science"
  },
  {
   "code": "CS 152",
   "section": "A",
   "title": "Computational Thinking: Science",
   "instructors": [
    "Allen Harper"
   ],
   "seatsTotal": 24,
   "seatsFilled": 24,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "11:00",
     "endTime": "11:50",
     "location": ""
    }
   ],
   "partialSchedule": true,
   "dept": "Computer Science"
  },
  {
   "code": "CS 166",
   "section": "A",
   "title": "Computational Thinking: Computer Vision",
   "instructors": [
    "Tahiya Chowdhury"
   ],
   "seatsTotal": 24,
   "seatsFilled": 13,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "M",
     "startTime": "13:00",
     "endTime": "14:20",
     "location": ""
    }
   ],
   "partialSchedule": true,
   "dept": "Computer Science"
  },
  {
   "code": "CS 231",
   "section": "A",
   "title": "Data Structures and Algorithms",
   "instructors": [
    "Naser Al Madi"
   ],
   "seatsTotal": 25,
   "seatsFilled": 13,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "11:00",
     "endTime": "11:50",
     "location": ""
    }
   ],
   "dept": "Computer Science"
  },
  {
   "code": "CS 231",
   "section": "B",
   "title": "Data Structures and Algorithms",
   "instructors": [
    "Naser Al Madi"
   ],
   "seatsTotal": 25,
   "seatsFilled": 14,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "12:00",
     "endTime": "12:50",
     "location": ""
    }
   ],
   "dept": "Computer Science"
  },
  {
   "code": "CS 232",
   "section": "A",
   "title": "Computer Organization",
   "instructors": [
    "Tahiya Chowdhury"
   ],
   "seatsTotal": 28,
   "seatsFilled": 26,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "09:00",
     "endTime": "09:50",
     "location": ""
    }
   ],
   "dept": "Computer Science"
  },
  {
   "code": "CS 251",
   "section": "A",
   "title": "Data Analysis and Visualization",
   "instructors": [
    "Oliver Layton"
   ],
   "seatsTotal": 25,
   "seatsFilled": 20,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "10:00",
     "endTime": "10:50",
     "location": ""
    }
   ],
   "dept": "Computer Science"
  },
  {
   "code": "CS 310",
   "section": "A",
   "title": "Creating Future Worlds: Computing, Ethics, and Society",
   "instructors": [
    "Stacy Doore"
   ],
   "seatsTotal": 28,
   "seatsFilled": 28,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "11:00",
     "endTime": "12:15",
     "location": ""
    }
   ],
   "crossList": [
    "CS 310-A",
    "ST 310-A"
   ],
   "dept": "Computer Science"
  },
  {
   "code": "CS 330",
   "section": "A",
   "title": "Real-World Database Design, Development, and Deployment",
   "instructors": [
    "Stacy Doore"
   ],
   "seatsTotal": 20,
   "seatsFilled": 17,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "09:30",
     "endTime": "10:45",
     "location": ""
    }
   ],
   "dept": "Computer Science"
  },
  {
   "code": "CS 331",
   "section": "A",
   "title": "Computer Networks",
   "instructors": [
    "Ying Li"
   ],
   "seatsTotal": 20,
   "seatsFilled": 14,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "09:30",
     "endTime": "10:45",
     "location": ""
    }
   ],
   "dept": "Computer Science"
  },
  {
   "code": "CS 333",
   "section": "A",
   "title": "Programming Languages",
   "instructors": [
    "Ying Li"
   ],
   "seatsTotal": 25,
   "seatsFilled": 20,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "MWF",
     "startTime": "10:00",
     "endTime": "10:50",
     "location": ""
    }
   ],
   "dept": "Computer Science"
  },
  {
   "code": "CS 343",
   "section": "A",
   "title": "Neural Networks",
   "instructors": [
    "Oliver Layton"
   ],
   "seatsTotal": 30,
   "seatsFilled": 30,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "09:30",
     "endTime": "10:45",
     "location": ""
    }
   ],
   "dept": "Computer Science"
  },
  {
   "code": "CS 375",
   "section": "A",
   "title": "Analysis of Algorithms",
   "instructors": [
    "Maximillian Bender"
   ],
   "seatsTotal": 23,
   "seatsFilled": 23,
   "status": "C",
   "rawStatus": "Waitlist",
   "credits": 4,
   "schedule": [
    {
     "days": "MW",
     "startTime": "13:00",
     "endTime": "14:15",
     "location": ""
    }
   ],
   "dept": "Computer Science"
  },
  {
   "code": "CS 386",
   "section": "A",
   "title": "Algorithmic Game Theory",
   "instructors": [
    "Maximillian Bender"
   ],
   "seatsTotal": 20,
   "seatsFilled": 19,
   "status": "O",
   "rawStatus": "Open",
   "credits": 4,
   "schedule": [
    {
     "days": "TR",
     "startTime": "14:30",
     "endTime": "15:45",
     "location": ""
    }
   ],
   "dept": "Computer Science"
  }
 ]
};
